apiVersion: v1
kind: Pod
metadata:
  name: mig-test-pod
spec:
  restartPolicy: Never
  containers:
  - name: cuda-container
    image: "nvidia/cuda:12.0-base"  # or any CUDA-based container
    command: ["nvidia-smi"]
    args: ["--query-gpu=gpu_uuid,mig.mode.current,mig.devices.current", "--format=csv"]
    resources:
      limits:
        # Request exactly one MIG slice (assuming 1g.5gb slices exist)
        nvidia.com/mig-1g.5gb: 1
